### ISSUE TITLE
20.04 compatibility

### ISSUE THREAD

**Issue by heuristicus** [ori-drs/procman_ros#19]
Currently sheriff does not run on focal:

```
rosrun procman_ros sheriff
Traceback (most recent call last):
  File "/home/michal/robots/drs/catkin_ws/devel/lib/procman_ros/sheriff", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/michal/robots/drs/catkin_ws/src/procman_ros/scripts/sheriff", line 2, in <module>
    import procman_ros.sheriff_gtk.sheriff_gtk
  File "/home/michal/robots/drs/catkin_ws/src/procman_ros/python/src/procman_ros/sheriff_gtk/sheriff_gtk.py", line 12, in <module>
    import glib
ModuleNotFoundError: No module named 'glib'
```

Suspect this is because PyGtk is no longer a thing: https://askubuntu.com/questions/97023/why-cant-i-import-pygtk-with-python-3-2-from-pydev

Likely that some changes to gui code will be necessary.

**Comment by heuristicus** [comment]
Need to check for

- `variable.set_data('some-label')`
- `variable.get_data('some-label')`

Both of these should be replaced by `variable.some_label` I think.

**Comment by heuristicus** [comment]
Useful gtk documentation for python: http://lazka.github.io/pgi-docs/

**Comment by heuristicus** [comment]
UI functionality checklist
# Top bar
## File
- [ ] load config
- [ ] save config
- [ ] preferences

## Options
- [ ] observer
- [ ] spawn local deputy
- [ ] terminate local deputy

##Commands
- [ ] start
- [ ] stop
- [ ] restart
- [ ] remove
- [ ] edit
- [ ] new

## scripts
- [ ] new
- [ ] edit
- [ ] remove
- [ ] abort

# Mouse interaction

- [ ] right clicking on groups
- [ ] right clicking on commands
- [ ] right clicking on deputies

**Comment by heuristicus** [comment]
When loading a configuration (`load_config` in sheriff_gtk), the `remove_command` call eventually leads to the function

```
   def command_removed(self, deputy_obj, cmd_obj):
        self._schedule_cmds_update()
        if self.cfg_to_load and not self.sheriff.get_all_commands():
            GLib.idle_add(self._do_load_config)
```

being called, and this triggers an assertion error for each command that exists in the previous configuration, because the initial call to `_do_load_config` from `load_config` clears the cfg_to_load attribute.

**Comment by heuristicus** [comment]
I fixed the properties dialog but the colour settings do not affect anything on 20.04, they are defined by the appearance settings of the OS.
