### ISSUE TITLE
Using ctrl-c to copy from the output gives an error

### ISSUE THREAD

**Issue by heuristicus** [ori-drs/procman_ros#26]
```
Traceback (most recent call last):
  File "/home/michal/robots/drs/catkin_ws/src/procman_ros/python/src/procman_ros/sheriff_gtk/command_console.py", line 266, in on_key_release
    self._tb_copy_selection()
  File "/home/michal/robots/drs/catkin_ws/src/procman_ros/python/src/procman_ros/sheriff_gtk/command_console.py", line 257, in _tb_copy_selection
    clipboard.set_text(text)
TypeError: Gtk.Clipboard.set_text() takes exactly 3 arguments (2 given)
```

**Comment by heuristicus** [comment]
Changing the error line to

```
clipboard.set_text(text, -1)
```

Results in more spam:

```
/home/michal/robots/drs/catkin_ws/src/procman_ros/python/src/procman_ros/sheriff_gtk/command_console.py:257: Warning: g_object_get_data: assertion 'G_IS_OBJECT (object)' failed
  clipboard.set_text(text, -1)

(sheriff:42423): Gdk-CRITICAL **: 15:29:20.537: gdk_display_get_default_screen: assertion 'GDK_IS_DISPLAY (display)' failed

(sheriff:42423): Gtk-CRITICAL **: 15:29:20.537: gtk_invisible_new_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
/home/michal/robots/drs/catkin_ws/src/procman_ros/python/src/procman_ros/sheriff_gtk/command_console.py:257: Warning: invalid (NULL) pointer instance
  clipboard.set_text(text, -1)
/home/michal/robots/drs/catkin_ws/src/procman_ros/python/src/procman_ros/sheriff_gtk/command_console.py:257: Warning: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  clipboard.set_text(text, -1)

(sheriff:42423): Gtk-CRITICAL **: 15:29:20.537: gtk_widget_add_events: assertion 'GTK_IS_WIDGET (widget)' failed
/home/michal/robots/drs/catkin_ws/src/procman_ros/python/src/procman_ros/sheriff_gtk/command_console.py:257: Warning: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed
  clipboard.set_text(text, -1)

(sheriff:42423): Gdk-CRITICAL **: 15:29:20.537: gdk_display_get_default_screen: assertion 'GDK_IS_DISPLAY (display)' failed

(sheriff:42423): Gtk-CRITICAL **: 15:29:20.537: gtk_invisible_new_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(sheriff:42423): Gtk-CRITICAL **: 15:29:20.537: gtk_widget_add_events: assertion 'GTK_IS_WIDGET (widget)' failed

(sheriff:42423): Gtk-CRITICAL **: 15:29:20.537: gtk_selection_owner_set_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(sheriff:42423): Gdk-CRITICAL **: 15:29:20.537: gdk_display_supports_clipboard_persistence: assertion 'GDK_IS_DISPLAY (display)' failed
```
